# Generated by Django 5.0.6 on 2024-07-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='episodios/')),
                ('duracion', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('serie', 'Serie'), ('pelicula', 'Película')], max_length=10)),
                ('fecha_transmision', models.IntegerField(blank=True, null=True)),
                ('temporada', models.IntegerField(blank=True, null=True)),
                ('numero_episodios', models.IntegerField(blank=True, null=True)),
                ('duracion_capitulo', models.DurationField(blank=True, null=True)),
                ('calidad', models.CharField(blank=True, max_length=20, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('episodios', models.ManyToManyField(blank=True, to='myapp.episodio')),
                ('genero', models.ManyToManyField(to='myapp.genero')),
                ('idiomas', models.ManyToManyField(to='myapp.idioma')),
                ('subtitulo', models.ManyToManyField(to='myapp.subtitulo')),
            ],
        ),
    ]
